### ISSUE TITLE
nolight flag makes newly generated parts of the world black

### ISSUE THREAD

**Issue by Calinou** [paramat/paragenv7#3]
![Image](https://lut.im/pEgm60Yz/WRnxoYaD)

This is on my server.

Even if you set the `light` flag afterwards, the black parts of the map stay there. WorldEdit's ``//fixlight`` doesn't help it either.

**Comment by Gael-de-Sailly** [comment]
My [mapfix](https://github.com/Gael-de-Sailly/mapfix) mod works for me.
About mapgen, I've corrected the problem, I'll make a PR.

**Comment by paramat** [comment]
This is weird. See comments in the PR.
